# Generated by Django 4.2.1 on 2023-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='remaining_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
