# Generated by Django 4.2.1 on 2023-05-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_soldproduct_remaining_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproduct',
            name='remaining_qty',
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
